/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dkqicodwthvchqfjwwwr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrcWljb2R3dGh2Y2hxZmp3d3dyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU1MDY0MTIsImV4cCI6MjA4MTA4MjQxMn0.Q-yHVGsMl3B_Uj7TaU0y1DgX0BX2P7qF_g-7F7kPdTM"